[package]
name = "kago"
version = "0.1.0"
authors = ["yutopp <yutopp@gmail.com>"]

[dependencies]
libc = "0.2.34"
log = "0.3.8"
simplelog = "0.4.3"
scopeguard = "0.3.3"
ipc-channel = "*"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.7"